app/user/models.py
from flask_login import UserMixin
from sqlalchemy import Column, Integer, String
from werkzeug.security import check_password_hash, generate_password_hash

from ..database import db
from ..login_manager import login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(50), unique=True, nullable=False)
    email_address = Column(String(50), unique=True, nullable=False)
    password_hash = Column(String(128), nullable=False)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, EmailField
from wtforms.validators import DataRequired, Length, Email, ValidationError

from .models import User


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

    def validate_username(self, field):
        user = User.query.filter_by(username=field.data).first()
        if not user:
            raise ValidationError('Invalid username.')

    def validate_password(self, field):
        user = User.query.filter_by(username=self.username.data).first()
        if user and not user.check_password(self.password.data):
            raise ValidationError('Invalid password.')


class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[
                           DataRequired(), Length(min=4, max=50)])
    email = EmailField('Email', validators=[
                       DataRequired(Email), Length(min=4, max=50)])
    password = PasswordField('Password', validators=[
                             DataRequired(), Length(min=4, max=50)])
    submit = SubmitField('Create account')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError(
                'Username already exists. Please choose a different username.')

    def validate_email(self, field):
        if User.query.filter_by(email_address=field.data).first():
            raise ValidationError(
                'Email address already exists. Please choose a different email address.')

app/user/routes.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import login_required, login_user, logout_user
from sqlalchemy.exc import IntegrityError

from ..database import db
from .forms import LoginForm, RegisterForm
from .models import User


user_bp = Blueprint('user', __name__, template_folder='templates')


@user_bp.route('/user/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('Logged in successfully!', 'success')

            return redirect(url_for('general.home'))

        else:
            flash('Invalid username or password', 'error')

    return render_template('user/login.html', form=form)


@user_bp.route('/user/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out successfully!', 'success')

    return redirect(url_for('general.home'))


@user_bp.route('/user/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(username=form.username.data,
                    email_address=form.email.data)
        user.set_password(form.password.data)
        
        try:
            db.session.add(user)
            db.session.commit()
            flash('Registered successfully! You can now login.', 'success')
            login_user(user)  # Automatically login the user after registration

            return redirect(url_for('general.home'))
        
        except IntegrityError:
            db.session.rollback()  # Rollback the transaction
            flash('Username already exists. Please choose a different username.', 'error')

    return render_template('user/register.html', form=form)

app/user/templates/user/login.html
{% extends 'user/user.html' %} 

{% block title %} Login form {% endblock title%}

{% block form %}

<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-item">
        <p class="control has-icons-left">
            {{ form.username(class="form-input input is-medium is-vcentered
            is-shadowless", type="text", placeholder="Username") }}
            <span class="icon is-small is-left is-flex is-align-items-center">
                <ion-icon name="person-outline"></ion-icon>
            </span>
        </p>
    </div>

    <div class="form-item">
        <p class="control has-icons-left">
            {{ form.password (class="form-input input is-medium is-shadowless",
            type="password", placeholder="Password")}}
            <span class="icon is-small is-left is-flex is-align-items-center">
                <ion-icon name="lock-closed-outline"></ion-icon>
            </span>
        </p>
    </div>

    <div>
        {% for error in form.username.errors %}
        <span class="form-error is-size-6 is-secondary-color">{{ error }}</span>
        {% endfor %}
        <br />
        {% for error in form.password.errors %}
        <span class="form-error is-size-6 is-secondary-color">{{ error }}</span>
        {% endfor %}
        <br />
    </div>

    <div>
        <span
            >Do not have account?
            <a
                class="signup-link has-text-weight-bold"
                href="{{ url_for('user.register') }}"
                >Sign up</a
            >
        </span>
    </div>

    {{ form.submit (class="button form-submit is-warning is-rounded is-outlined
    is-uppercase has-text-weight-bold", value="Login") }}
</form>

{% endblock form %}

app/user/templates/user/register.html
{% extends 'user/user.html' %}

{% block title %} Register form {% endblock title%}

{% block form %}

<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-item">
        <p class="control has-icons-left">
            {{ form.username(class="form-input input is-medium is-vcentered
            is-shadowless", type="text", placeholder="Username") }}
            <span class="icon is-small is-left is-flex is-align-items-center">
                <ion-icon name="person-outline"></ion-icon>
            </span>
        </p>
    </div>

    <div class="form-item">
        <p class="control has-icons-left">
            {{ form.email (class="form-input input is-medium is-shadowless",
            type="email", placeholder="Email")}}
            <span class="icon is-small is-left is-flex is-align-items-center">
                <ion-icon name="mail-outline"></ion-icon>
            </span>
        </p>
    </div>

    <div class="form-item">
        <p class="control has-icons-left">
            {{ form.password (class="form-input input is-medium is-shadowless",
            type="password", placeholder="Password")}}
            <span class="icon is-small is-left is-flex is-align-items-center">
                <ion-icon name="lock-closed-outline"></ion-icon>
            </span>
        </p>
    </div>

    <div>
        {% for error in form.username.errors %}
        <span class="form-error is-size-6 is-secondary-color">{{ error }}</span>
        {% endfor %}
        <br />
        {% for error in form.email.errors %}
        <span class="form-error is-size-6 is-secondary-color">{{ error }}</span>
        {% endfor %}
        <br />
    </div>

    {{ form.submit (class="button form-submit is-warning is-rounded is-outlined
    is-uppercase has-text-weight-bold", value="Create account") }}
</form>

{% endblock form %}

app/user/templates/user/user.html
{% extends 'general/base.html' %}

{% block content %}

<section class="hero is-fullheight is-fullheight-with-navbar">
    <div class="hero-body">
        <div class="container">
            <div class="columns">
                <div class="column is-3-desktop"></div>
                <div
                    class="column is-half-desktop is-fullwidth-tablet is-fullwidth-mobile is-centered has-text-centered"
                >
                    <h2
                        class="subtitle is-size-3 is-uppercase is-secondary-color"
                    >
                        {% block title %} {% endblock title%}
                    </h2>

                    {% block form %} {% endblock form %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}