app/general/routes.py
from flask import Blueprint, render_template


general_bp = Blueprint('general', __name__, template_folder='templates')


@general_bp.route('/')
def home():
    return render_template('general/home.html')


@general_bp.route('/about')
def about():
    return render_template('general/about.html')

app/general/templates/general/about.html
{% extends 'general/base.html' %} {% block content %}

<section class="hero is-halfheight">
    <div class="hero-body">
        <div class="container">
            <div
                class="columns is-flex is-justify-content-center is-vcentered has-text-centered"
            >
                <div class="column is-7">
                    <h2 class="is-size-2 mb-4 is-secondary-color is-uppercase">
                        The Bakery: A Tale of Passion and Flour
                    </h2>
                    <p class="is-size-5 mb-6">
                        Welcome, dear friends, to the Bakery!
                        <br />
                        As the small yellow bird behind this magical venture, I
                        am thrilled to share with you the story of how this
                        dream bakery came to be. From the moment I hatched from
                        my cozy nest, I knew that my destiny lay in the world of
                        baking. The aroma of fresh baked goods and the sight of
                        golden pastries dancing in the morning sunlight ignited
                        a fire within me, a passion that would guide me on an
                        extraordinary journey.
                    </p>
                </div>
                <div class="column is-3 is-offset-1">
                    <figure class="image is-2by3">
                        <img
                            src="{{ url_for('static', filename='img/dreaming-sunny.png')}}"
                            alt="dreaming-sunny"
                        />
                    </figure>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="hero is-halfheight">
    <div class="hero-body">
        <div class="container">
            <div
                class="columns is-flex is-justify-content-center is-vcentered has-text-centered"
            >
                <div class="column is-3">
                    <figure class="image is-2by3">
                        <img
                            src="{{ url_for('static', filename='img/learning-sunny.png')}}"
                            alt="learning-sunny"
                        />
                    </figure>
                </div>
                <div class="column is-7 is-offset-1">
                    <p class="is-size-5 mb-6">
                        With determination in my heart and a sprinkle of
                        curiosity, I embarked on a quest to learn the art of
                        baking. I sought wisdom from the wise old owl, who
                        generously shared the secrets of kneading dough and
                        coaxing flavors from simple ingredients. With each
                        lesson learned, my dream grew brighter, fueling my
                        desire to create something truly special. Through
                        countless hours of practice and experimentation, I honed
                        my skills and crafted recipes that captured the essence
                        of joy and warmth. From fluffy rolls to decadent cakes
                        adorned with berries plucked from the forest, every
                        creation was a labor of love, infused with the magic of
                        the forest that surrounded me.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="hero is-halfheight">
    <div class="hero-body">
        <div class="container">
            <div
                class="ccolumns is-flex is-justify-content-center is-vcentered has-text-centered"
            >
                <div class="column is-7">
                    <p class="is-size-5 mb-6">
                        When the time came to share my creations with the world,
                        I knew that I had found the perfect spot for my dream
                        bakery. In a quaint clearing bathed in sunlight and
                        serenaded by the gentle rustle of leaves, the Bakery
                        came to life. With the help of my forest friends, we
                        transformed the space into a whimsical haven, where the
                        scent of freshly baked goods mingled with the laughter
                        of customers. Word of our little bakery spread like
                        wildfire, drawing creatures from far and wide to sample
                        our delights. From busy bees buzzing in for
                        honey-sweetened treats to sleepy owls seeking a
                        pick-me-up from our aromatic coffee, each visitor added
                        to the vibrant tapestry of life that filled our bakery
                        with warmth and joy.
                    </p>
                </div>
                <div class="column is-3 is-offset-1">
                    <figure class="image is-square">
                        <img
                            src="{{ url_for('static', filename='img/cooking-sunny.png')}}"
                            alt="cooking-sunny"
                        />
                    </figure>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="hero is-halfheight">
    <div class="hero-body">
        <div class="container">
            <div
                class="columns is-flex is-justify-content-center is-vcentered has-text-centered"
            >
                <div class="column is-3">
                    <figure class="image">
                        <img
                            src="{{ url_for('static', filename='img/baking-left.png')}}"
                            alt="baking-left"
                        />
                    </figure>
                </div>
                <div class="column is-6">
                    <p class="is-size-5 mb-6">
                        Beyond the hustle and bustle of daily life, what truly
                        fills my heart with happiness is knowing that I have
                        found my purpose, my calling in life. To create moments
                        of sweetness and delight, to bring smiles to the faces
                        of those who walk through our doors that is the true
                        magic of the Bakery. So, dear friends, I invite you to
                        join us on this enchanting journey. Whether you're a
                        curious traveler passing through the forest or a local
                        seeking a taste of home, know that you are always
                        welcthe the Bakery, where every treat tells a story of
                        passion and flour.
                        <br />
                        With love and gratitude, Sunny
                    </p>
                </div>
                <div class="column is-3">
                    <figure class="image">
                        <img
                            src="{{ url_for('static', filename='img/baking-right.png')}}"
                            alt="baking-right"
                        />
                    </figure>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

app/general/templates/general/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>BAKERY</title>
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css"
        />
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='css/styles.css') }}"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
            rel="stylesheet"
        />

        <script
            type="module"
            src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
        ></script>
        <script
            nomodule
            src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
        ></script>

        <script
            defer
            src="{{ url_for('static', filename='js/scripts.js') }}"
        ></script>
    </head>

    <body class="has-navbar-fixed-top">
        {% include('general/includes/navigation.html') %} 

        {% block content %} {% endblock content %}

        {% include('general/includes/footer.html') %}
    </body>
</html>

app/general/templates/general/footer.html
<footer class="section is-secondary-color">
    <div class="container">
        <div class="columns has-text-centered">
            <div class="column is-one-third">
                <p
                    class="is-size-6 is-uppercase has-text-weight-bold my-5"
                >
                    About
                </p>

                <ul class="links about is-block is-vcentered">
                    <li>
                        <a class="footer-item" href="{{ url_for('general.about')}}">
                            Our Story
                        </a>
                    </li>
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            Products
                        </a>
                    </li>
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            Create Your Own
                        </a>
                    </li>
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            Locations
                        </a>
                    </li>
                </ul>
            </div>

            <div class="column is-one-third">
                <p
                    class="is-size-6 is-uppercase has-text-weight-bold my-5"
                >
                    Connecting with us
                </p>

                <ul class="links contact is-inline-flex is-vcentered">
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            <img
                                src="{{ url_for('static', filename='img/mail-outline.svg')}}"
                                alt="logo-instagram"
                            />
                        </a>
                    </li>
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            <img
                                src="{{ url_for('static', filename='img/logo-twitter.svg')}}"
                                alt="logo-twitter"
                            />
                        </a>
                    </li>
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            <img
                                class="footer-item"
                                src="{{ url_for('static', filename='img/logo-facebook.svg')}}"
                                alt="logo-facebook"
                            />
                        </a>
                    </li>

                    <li>
                        <a class="footer-item" href="" target="_blank">
                            <img
                                src="{{ url_for('static', filename='img/logo-instagram.svg')}}"
                                alt="logo-instagram"
                            />
                        </a>
                    </li>
                </ul>
            </div>

            <div class="column is-one-third">
                <p
                    class="is-size-6 is-uppercase has-text-weight-bold my-5"
                >
                    Help
                </p>

                <ul class="links help is-block is-vcentered">
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            Account
                        </a>
                    </li>
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            Delivery
                        </a>
                    </li>
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            Contact Us
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container has-text-centered">
        <div class="columns is-centered">
            <div class="column is-9">
                <p id="copyright">
                    Website designed and created by Kate Kochina. The source
                    code is licensed
                    <a href="http://opensource.org/licenses/mit-license.php"
                        >MIT</a
                    >.
                </p>
            </div>
        </div>
    </div>
</footer>

app/general/templates/general/home.html
{% extends 'general/base.html' %} {% block content %}

<section class="hero is-fullheight is-fullheight-with-navbar">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-flex is-justify-content-center">
                <div class="column is-8">
                    <figure class="image is-16by9">
                        <img
                            src="{{ url_for('static', filename='img/home.png')}}"
                            alt="home-img"
                        />
                    </figure>
                </div>
            </div>

            <div
                class="columns is-flex is-justify-content-center has-text-centered"
            >
                <div class="column is-6">
                    <h2 class="is-size-2 mb-4 is-secondary-color">
                        WELCOME TO THE BAKERY
                    </h2>
                    <p class="is-size-5 mb-6">
                        Embark on a delightful journey with our freshly crafted
                        delights, meticulously made from premium ingredients.
                        Enhance your moments with the irresistible allure of our
                        treats, ensuring a joyous and festive experience for you
                    </p>

                    <button
                        class="button is-primary is-rounded is-outlined"
                        href="{{ url_for('products.show_products') }}"
                    >
                        <strong>MAKE ORDER</strong>
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="hero is-fullheight">
    <div class="hero-body">
        <div class="container">
            <div
                class="columns is-flex is-justify-content-center has-text-centered is-vcentered"
            >
                <div class="column is-4">
                    <figure class="image">
                        <img
                            src="{{ url_for('static', filename='img/create-own.png')}}"
                            alt="create-own-img"
                        />
                    </figure>
                </div>
                <div class="column is-1"></div>
                <div class="column is-5">
                    <p class="is-size-5 mb-6">
                        With the bakery, here is a space where you have the
                        opportunity to explore your imagination and craft your
                        own one-of-a-kind baked creations
                    </p>
                    <a class="button is-primary is-rounded is-outlined">
                        <strong>CREATE YOUR OWN</strong>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

app/general/templates/general/includes/_footer.html
<footer class="section is-secondary-color">
    <div class="container">
        <div class="columns has-text-centered has-text-weight-bold">
            <div class="column is-one-third">
                <p
                    class="is-size-5 is-uppercase my-5"
                >
                    About
                </p>

                <ul class="links about is-block is-vcentered">
                    <li>
                        <a class="footer-item is-size-6" href="{{ url_for('general.about')}}">
                            Our Story
                        </a>
                    </li>
                    <li>
                        <a class="footer-item is-size-6" href="{{ url_for('products.show_products') }}">
                            Products
                        </a>
                    </li>
                    <li>
                        <a class="footer-item is-size-6" href="#">
                            Create Your Own
                        </a>
                    </li>
                    <li>
                        <a class="footer-item is-size-6" href="" target="_blank">
                            Locations
                        </a>
                    </li>
                </ul>
            </div>

            <div class="column is-one-third">
                <p
                    class="is-size-5 is-uppercase my-5"
                >
                    Connecting with us
                </p>

                <ul class="links contact is-inline-flex is-vcentered">
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            <img
                                src="{{ url_for('static', filename='img/mail-outline.svg')}}"
                                alt="logo-instagram"
                            />
                        </a>
                    </li>
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            <img
                                src="{{ url_for('static', filename='img/logo-twitter.svg')}}"
                                alt="logo-twitter"
                            />
                        </a>
                    </li>
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            <img
                                class="footer-item"
                                src="{{ url_for('static', filename='img/logo-facebook.svg')}}"
                                alt="logo-facebook"
                            />
                        </a>
                    </li>

                    <li>
                        <a class="footer-item" href="" target="_blank">
                            <img
                                src="{{ url_for('static', filename='img/logo-instagram.svg')}}"
                                alt="logo-instagram"
                            />
                        </a>
                    </li>
                </ul>
            </div>

            <div class="column is-one-third">
                <p
                    class="is-size-5 is-uppercase my-5"
                >
                    Help
                </p>

                <ul class="links help is-block is-vcentered">
                    <li>
                        <a class="footer-item is-size-6" href="" target="_blank">
                            Account
                        </a>
                    </li>
                    <li>
                        <a class="footer-item is-size-6" href="" target="_blank">
                            Delivery
                        </a>
                    </li>
                    <li>
                        <a class="footer-item is-size-6" href="" target="_blank">
                            Contact Us
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container has-text-centered">
        <div class="columns is-centered">
            <div class="column is-9">
                <p id="copyright">
                    Website designed and created by Kate Kochina. The source
                    code is licensed
                    <a href="http://opensource.org/licenses/mit-license.php"
                        >MIT</a
                    >.
                </p>
            </div>
        </div>
    </div>
</footer>

app/general/templates/general/includes/_navigation.html
<nav class="navbar is-spaced" role="navigation" aria-label="main navigation">
    <div class="navbar-brand is-flex is-justify-content-center">
        <a class="navbar-item" href="{{url_for('general.home')}}">
            <img
                src="{{ url_for('static', filename='img/logo.png')}}"
                alt="logo"
            />
        </a>
        <a
            role="button"
            class="navbar-burger"
            aria-label="menu"
            aria-expanded="false"
            data-target="nav-menu"
        >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="nav-menu" class="navbar-menu is-shadowless has-text-weight-bold">
        <div class="navbar-start is-flex is-justify-content-center"></div>
        <div class="navbar-end is-flex is-justify-content-center">
            <a class="navbar-item is-size-5" href="{{ url_for('products.show_products') }}"> Products </a>

            <a class="navbar-item is-size-5" href="{{ url_for('general.about') }}">
                About
            </a>
            <a class="navbar-item is-size-5" href=""> Login </a>

            <a class="navbar-item" href="">
                <img
                    src="{{ url_for('static', filename='img/cart-outline.svg')}}"
                    alt="cart-img"
                />
            </a>
        </div>
    </div>
</nav>

app/general/templates/general/includes/footer.html
<footer class="section is-secondary-color">
    <div class="container">
        <div class="columns has-text-centered">
            <div class="column is-one-third">
                <p class="is-size-5 has-text-weight-bold is-uppercase my-5">
                    About
                </p>

                <ul class="links about is-block is-vcentered">
                    <li>
                        <a
                            class="footer-item is-size-6"
                            href="{{ url_for('general.about')}}"
                        >
                            Our Story
                        </a>
                    </li>
                    <li>
                        <a
                            class="footer-item is-size-6"
                            href="{{ url_for('products.show_products') }}"
                        >
                            Products
                        </a>
                    </li>
                    <li>
                        <a class="footer-item is-size-6" href="#">
                            Create Your Own
                        </a>
                    </li>
                    <li>
                        <a
                            class="footer-item is-size-6"
                            href=""
                            target="_blank"
                        >
                            Locations
                        </a>
                    </li>
                </ul>
            </div>

            <div class="column is-one-third">
                <p class="is-size-5 has-text-weight-bold is-uppercase my-5">
                    Connecting with us
                </p>

                <ul class="links contact is-inline-flex is-vcentered">
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            <ion-icon
                                size="large"
                                name="mail-outline"
                            ></ion-icon>
                        </a>
                    </li>
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            <ion-icon
                                size="large"
                                name="logo-twitter"
                            ></ion-icon>
                        </a>
                    </li>
                    <li>
                        <a class="footer-item" href="" target="_blank">
                            <ion-icon
                                size="large"
                                name="logo-facebook"
                            ></ion-icon>
                        </a>
                    </li>

                    <li>
                        <a class="footer-item" href="" target="_blank">
                            <ion-icon
                                size="large"
                                name="logo-instagram"
                            ></ion-icon>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="column is-one-third">
                <p class="is-size-5 has-text-weight-bold is-uppercase my-5">
                    Help
                </p>

                <ul class="links help is-block is-vcentered">
                    <li>
                        <a
                            class="footer-item is-size-6"
                            href=""
                            target="_blank"
                        >
                            Account
                        </a>
                    </li>
                    <li>
                        <a
                            class="footer-item is-size-6"
                            href=""
                            target="_blank"
                        >
                            Delivery
                        </a>
                    </li>
                    <li>
                        <a
                            class="footer-item is-size-6"
                            href=""
                            target="_blank"
                        >
                            Contact Us
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container has-text-centered">
        <div class="columns is-centered">
            <div class="column is-9">
                <p id="copyright">
                    Website designed and created by Kate Kochina. The source
                    code is licensed
                    <a href="http://opensource.org/licenses/mit-license.php"
                        >MIT</a
                    >.
                </p>
            </div>
        </div>
    </div>
</footer>

app/general/templates/general/includes/navigation.html
<nav
    class="navbar is-spaced is-fixed-top"
    role="navigation"
    aria-label="main navigation"
>
    <div class="navbar-brand is-flex is-justify-content-center">
        <a class="navbar-item" href="{{url_for('general.home')}}">
            <img
                src="{{ url_for('static', filename='img/logo.png')}}"
                alt="logo"
            />
        </a>
        <a
            role="button"
            class="navbar-burger"
            aria-label="menu"
            aria-expanded="false"
            data-target="nav-menu"
        >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="nav-menu" class="navbar-menu is-shadowless has-text-weight-bold">
        <div class="navbar-start is-flex is-justify-content-center"></div>
        <div class="navbar-end is-flex is-justify-content-center">
            <a
                class="navbar-item is-uppercase is-size-5"
                href="{{ url_for('products.show_products') }}"
            >
                Products
            </a>

            <a
                class="navbar-item is-uppercase is-size-5"
                href="{{ url_for('general.about') }}"
            >
                About
            </a>
            {% if current_user.is_authenticated %}
            <a
                class="navbar-item is-uppercase is-size-5"
                href="{{ url_for('user.logout') }}"
                >Logout</a
            >
            <a class="navbar-item" href="{{ url_for('cart.view_cart')}}">
                <ion-icon size="large" name="cart-outline"></ion-icon>
            </a>
            {% else %}
            <a
                class="navbar-item is-uppercase is-size-5"
                href="{{ url_for('user.login') }}"
                >Login</a
            >
            {% endif %}
        </div>
    </div>
</nav>

app/general/templates/general/navigation.html
<nav class="navbar is-spaced" role="navigation" aria-label="main navigation">
    <div class="navbar-brand is-flex is-justify-content-center">
        <a class="navbar-item" href="{{url_for('general.home')}}">
            <img
                src="{{ url_for('static', filename='img/logo.png')}}"
                alt="logo"
            />
        </a>
        <a
            role="button"
            class="navbar-burger"
            aria-label="menu"
            aria-expanded="false"
            data-target="nav-menu"
        >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="nav-menu" class="navbar-menu is-shadowless has-text-weight-bold">
        <div class="navbar-start is-flex is-justify-content-center"></div>
        <div class="navbar-end is-flex is-justify-content-center">
            <a class="navbar-item" href=""> Products </a>

            <a class="navbar-item" href="{{ url_for('general.about') }}">
                About
            </a>
            <a class="navbar-item" href=""> Login </a>

            <a class="navbar-item" href="">
                <img
                    src="{{ url_for('static', filename='img/cart-outline.svg')}}"
                    alt="cart-img"
                />
            </a>
        </div>
    </div>
</nav>